# Generated by Django 4.2.6 on 2023-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
